Fix: runtime error with missing type
System.TypeLoadException: Could not load type 'System.Linq.ParallelEnumerable' from assembly 'Microsoft.Extensions.Configuration.Json, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

This is due to publishing trimmed package to reduce size.